-- ============================================================
-- OriginHash - Login & User Management module
-- Raw SQL used to design the database tables.
-- Sequelize will also auto-create/sync these same tables on
-- server start, but this file is provided so you can create
-- the schema by hand if you prefer, or review exactly what
-- Sequelize is generating.
-- ============================================================

CREATE DATABASE IF NOT EXISTS originhash
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE originhash;

-- ------------------------------------------------------------
-- Table: users
-- Holds Super-admins, Admins, and normal app users
-- (Farmer / Retailer / Distributor / Supplier / Consumer).
-- Normal users log in with mobile + OTP (mobile required, no
-- username/password). Admin and Super-admin accounts log in
-- with username + password instead (mobile optional, OTP login
-- is rejected for is_admin = 1 accounts). is_super_admin further
-- distinguishes accounts that can manage other admin accounts.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id                  INT UNSIGNED NOT NULL AUTO_INCREMENT,
  mobile              VARCHAR(15)  NULL,
  country_code        VARCHAR(5)   NOT NULL DEFAULT '+91',
  username            VARCHAR(50)  NULL,
  password_hash       VARCHAR(255) NULL,
  name                VARCHAR(120) NULL,
  email               VARCHAR(150) NULL,
  photo_url           VARCHAR(500) NULL,
  user_type           ENUM('farmer','retailer','distributor','supplier','consumer') NULL,
  address             VARCHAR(255) NULL,
  is_admin            TINYINT(1)   NOT NULL DEFAULT 0,
  is_super_admin      TINYINT(1)   NOT NULL DEFAULT 0,
  is_blocked          TINYINT(1)   NOT NULL DEFAULT 0,
  profile_completed   TINYINT(1)   NOT NULL DEFAULT 0,
  scans_count         INT UNSIGNED NOT NULL DEFAULT 0,
  created_at          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_mobile (mobile),
  UNIQUE KEY uq_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: user_profile_versions
-- Every saved state of a user's identifying details, so admins can
-- tell that batches generated as "Harish" and later as "Kumar" came
-- from the same account. Rows are only ever added: a new version is
-- written whenever name / email / address / user type / mobile
-- changes (source 'self' = the user, 'admin' = an admin, see
-- changed_by, 'system' = recorded automatically — existing users'
-- details when history started, or details first seen at QR
-- generation). Empty values are stored as NULL.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_profile_versions (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id      INT UNSIGNED NOT NULL,
  version_no   INT UNSIGNED NOT NULL,  -- 1, 2, 3, … per user
  name         VARCHAR(120) NULL,
  email        VARCHAR(150) NULL,
  address      VARCHAR(255) NULL,
  user_type    VARCHAR(20)  NULL,
  mobile       VARCHAR(15)  NULL,
  source       VARCHAR(10)  NOT NULL,  -- 'self' | 'admin' | 'system'
  changed_by   INT UNSIGNED NULL,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_user_profile_versions_user_version (user_id, version_no),
  CONSTRAINT fk_user_profile_versions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_profile_versions_editor FOREIGN KEY (changed_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: otps
-- Stores one-time-passwords issued for login/registration.
-- In this static/demo phase, the OTP is generated by the
-- backend and returned to the frontend to display on screen
-- (no SMS provider wired up yet - 2Factor to be added later).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS otps (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  mobile       VARCHAR(15)  NOT NULL,
  otp_code     VARCHAR(10)  NOT NULL,
  expires_at   DATETIME     NOT NULL,
  is_used      TINYINT(1)   NOT NULL DEFAULT 0,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_otps_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: image_folders / image_assets
-- Admin "Image stock" library: images are organised into
-- named folders and uploaded to S3 under image-stock/<folder name>/.
-- is_sample marks folders made by "Generate sample folder" (10
-- photos of different animals / people from iNaturalist); only
-- those can be deleted. Deleting sets deleted_at (the row stays so
-- QR batches made from it keep their folder), removes its
-- image_assets, and removes from S3 only photos no sticker uses.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS image_folders (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name         VARCHAR(120) NOT NULL,
  is_sample    TINYINT(1)   NOT NULL DEFAULT 0,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at   DATETIME     NULL,  -- set when a sample folder is deleted; hidden everywhere
  PRIMARY KEY (id),
  UNIQUE KEY uq_image_folders_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS image_assets (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  serial_no    INT UNSIGNED NULL,  -- gap-free image number 1, 2, 3, … in upload order; NULL in sample folders
  folder_id    INT UNSIGNED NOT NULL,
  file_name    VARCHAR(255) NOT NULL,
  url          VARCHAR(500) NOT NULL,
  width        INT UNSIGNED NULL,
  height       INT UNSIGNED NULL,
  size_bytes   INT UNSIGNED NULL,
  mime_type    VARCHAR(50)  NULL,
  file_hash    VARCHAR(64)  NOT NULL,
  is_blocked   TINYINT(1)   NOT NULL DEFAULT 0,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_image_assets_folder_hash (folder_id, file_hash),
  UNIQUE KEY uq_image_assets_serial (serial_no),
  CONSTRAINT fk_image_assets_folder FOREIGN KEY (folder_id) REFERENCES image_folders (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: qr_batches / qr_codes
-- Admin "Generate QR stickers" tool. One batch = one generation
-- run (producer/product/batch details + a source image folder).
-- Each qr_codes row is one physical unit with its own unique
-- code and a randomly-assigned image from the batch's folder.
-- The PDF export prints 3 sets per batch (1 customer + 2
-- reference) — same codes/images, just extra physical copies.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS qr_batches (
  id             INT UNSIGNED NOT NULL AUTO_INCREMENT,
  producer       VARCHAR(150) NOT NULL,
  product_name   VARCHAR(150) NOT NULL,
  variant_size   VARCHAR(150) NULL,
  batch_no       VARCHAR(80)  NOT NULL,  -- unique across batches (checked by the API, case-insensitive)
  split_type     ENUM('vertical-50-50','horizontal-50-50') NOT NULL DEFAULT 'vertical-50-50',
  page_size      VARCHAR(2)   NULL,  -- 'A4' or 'A3' for the sticker PDF; NULL (older batches) = A4
  number_of_qrs  INT UNSIGNED NOT NULL,
  folder_id      INT UNSIGNED NOT NULL,
  created_by     INT UNSIGNED NULL,  -- user who generated the batch; sees its stickers' full journeys
  creator_profile_version_id INT UNSIGNED NULL,  -- creator's details at generation time; NULL for older batches
  created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_qr_batches_folder FOREIGN KEY (folder_id) REFERENCES image_folders (id),
  CONSTRAINT fk_qr_batches_creator FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_qr_batches_creator_profile FOREIGN KEY (creator_profile_version_id) REFERENCES user_profile_versions (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qr_codes (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid          CHAR(36)     NULL,  -- public "QR ID"; filled on server start for older rows
  batch_id      INT UNSIGNED NOT NULL,
  sequence_no   INT UNSIGNED NOT NULL,
  code          VARCHAR(60)  NULL,
  image_url     VARCHAR(500) NOT NULL,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_qr_codes_code (code),
  UNIQUE KEY uq_qr_codes_uuid (uuid),
  CONSTRAINT fk_qr_codes_batch FOREIGN KEY (batch_id) REFERENCES qr_batches (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: scans
-- One row per scan a user makes in the app.
-- action 'record' logs that a product reached this user
-- (supply-chain movement, with the device location when shared):
--   result SCANNED.
-- action 'verify' checks a product by revealing its sticker image
-- once and asking the user whether it matches:
--   PENDING        started, not answered yet
--   MATCHED        user confirmed the image matches
--   UNMATCHED      user said it doesn't match
--   ROLLED_BACK    user backed out / left before answering
--   NOT_FOUND      code isn't in qr_codes
--   INVALID        QR wasn't an OriginHash sticker
--   ALREADY_VIEWED sticker image was already revealed once
--   AUTHENTIC      legacy, before the image-match step
-- image_revealed_at is set on the single scan that revealed a
-- sticker's image; each sticker's image is shown only once.
-- qr_code_id is NULL when the code matched nothing.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scans (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid         CHAR(36)     NULL,  -- public "Scan ID"; filled on server start for older rows
  user_id      INT UNSIGNED NOT NULL,
  qr_code_id   INT UNSIGNED NULL,
  code         VARCHAR(60)  NULL,
  action       ENUM('record','verify') NOT NULL,
  result       VARCHAR(20)  NOT NULL,
  latitude     DECIMAL(9,6) NULL,
  longitude    DECIMAL(9,6) NULL,
  location_name VARCHAR(255) NULL, -- place name for the coordinates (OpenStreetMap Nominatim)
  image_revealed_at DATETIME NULL,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_scans_uuid (uuid),
  CONSTRAINT fk_scans_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_scans_qr_code FOREIGN KEY (qr_code_id) REFERENCES qr_codes (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: scan_reports
-- A user's report about a scanned product: sent with an
-- "Unmatched" answer (which closes the scan as UNMATCHED) or from
-- an "Already verified" (ALREADY_VIEWED) result. One per scan;
-- the note and photo (stored in S3 under scan-reports/) are both
-- optional.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scan_reports (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  scan_id      INT UNSIGNED NOT NULL,
  note         TEXT         NULL,
  photo_url    VARCHAR(500) NULL,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_scan_reports_scan (scan_id),
  CONSTRAINT fk_scan_reports_scan FOREIGN KEY (scan_id) REFERENCES scans (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Seed: default Admin account
-- Mobile: 7816018884, static login OTP: 8884
-- (also created automatically by src/utils/seedAdmin.js on boot)
-- ------------------------------------------------------------
INSERT INTO users
  (mobile, country_code, name, is_admin, is_blocked, profile_completed, created_at, updated_at)
VALUES
  ('7816018884', '+91', 'Admin', 1, 0, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE is_admin = 1;

-- ------------------------------------------------------------
-- Example queries used by the API (for reference)
-- ------------------------------------------------------------

-- Find a user by mobile (used at login):
-- SELECT * FROM users WHERE mobile = ? LIMIT 1;

-- Create a new normal user on first OTP request:
-- INSERT INTO users (mobile, country_code, is_admin, is_blocked, profile_completed, created_at, updated_at)
-- VALUES (?, '+91', 0, 0, 0, NOW(), NOW());

-- Store a freshly generated OTP:
-- INSERT INTO otps (mobile, otp_code, expires_at, is_used, created_at)
-- VALUES (?, ?, ?, 0, NOW());

-- Validate an OTP at verify time:
-- SELECT * FROM otps
-- WHERE mobile = ? AND otp_code = ? AND is_used = 0 AND expires_at >= NOW()
-- ORDER BY id DESC LIMIT 1;

-- Mark OTP used:
-- UPDATE otps SET is_used = 1 WHERE id = ?;

-- Update own profile (normal user):
-- UPDATE users
-- SET name = ?, email = ?, user_type = ?, address = ?, photo_url = ?, profile_completed = 1, updated_at = NOW()
-- WHERE id = ?;

-- List users for Admin (search + status filter):
-- SELECT * FROM users
-- WHERE is_admin = 0
--   AND (name LIKE CONCAT('%', ?, '%') OR mobile LIKE CONCAT('%', ?, '%'))
--   AND (? IS NULL OR is_blocked = ?)
-- ORDER BY created_at DESC;

-- Record a profile version (after any profile save, and when generating QRs) —
-- only if a tracked field differs from the latest version:
-- SELECT * FROM user_profile_versions WHERE user_id = ? ORDER BY version_no DESC LIMIT 1;
-- INSERT INTO user_profile_versions (user_id, version_no, name, email, address, user_type, mobile, source, changed_by, created_at)
-- VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NOW());

-- A user's profile history for admins (GET /api/users/:id/history):
-- SELECT * FROM user_profile_versions WHERE user_id = ? ORDER BY version_no;
-- SELECT * FROM qr_batches WHERE created_by = ? ORDER BY created_at DESC;

-- Block / unblock a user:
-- UPDATE users SET is_blocked = 1 WHERE id = ?;
-- UPDATE users SET is_blocked = 0 WHERE id = ?;

-- Admin adds a user manually:
-- INSERT INTO users (mobile, country_code, name, email, user_type, address, is_admin, is_blocked, profile_completed, created_at, updated_at)
-- VALUES (?, '+91', ?, ?, ?, ?, 0, 0, 1, NOW(), NOW());

-- Record / verify a scan (POST /api/scans):
-- SELECT * FROM qr_codes WHERE code = ? LIMIT 1;
-- INSERT INTO scans (user_id, qr_code_id, code, action, result, latitude, longitude, created_at)
-- VALUES (?, ?, ?, ?, ?, ?, ?, NOW());
-- UPDATE users SET scans_count = scans_count + 1 WHERE id = ?;

-- Reveal a sticker's image (POST /api/scans/:id/reveal) — refused if it was revealed before:
-- SELECT * FROM qr_codes WHERE id = ? FOR UPDATE;
-- SELECT * FROM scans WHERE qr_code_id = ? AND image_revealed_at IS NOT NULL AND id <> ?
-- ORDER BY image_revealed_at LIMIT 1;
-- UPDATE scans SET image_revealed_at = NOW() WHERE id = ?;

-- Answer or back out of a verification (PATCH /api/scans/:id):
-- UPDATE scans SET result = ? WHERE id = ? AND user_id = ? AND result = 'PENDING';

-- Report a product (POST /api/scans/:id/report):
-- UPDATE scans SET result = 'UNMATCHED' WHERE id = ? AND result = 'PENDING';  -- only for an open verification
-- INSERT INTO scan_reports (scan_id, note, photo_url, created_at) VALUES (?, ?, ?, NOW());

-- Home screen totals and latest scans (GET /api/scans/summary):
-- SELECT action, result, COUNT(id) AS count FROM scans WHERE user_id = ? GROUP BY action, result;
-- SELECT * FROM scans WHERE user_id = ? ORDER BY id DESC LIMIT 5;

-- Scan history, newest first, 20 per page (GET /api/scans?filter=&before=):
-- SELECT * FROM scans WHERE user_id = ? [AND result IN (...)] [AND id < ?] ORDER BY id DESC LIMIT 21;

-- One scan's details + the sticker's journey (GET /api/scans/:id):
-- SELECT s.*, u.name, u.user_type FROM scans s JOIN users u ON u.id = s.user_id
-- WHERE s.qr_code_id = ? AND s.result = 'SCANNED' ORDER BY s.id LIMIT 50;
-- SELECT * FROM scans WHERE qr_code_id = ? AND result IN ('MATCHED','AUTHENTIC') ORDER BY id LIMIT 1;
