-- ============================================================
-- OriginHash - Login & User Management module
-- Raw SQL used to design the database tables.
-- Sequelize will also auto-create/sync these same tables on
-- server start, but this file is provided so you can create
-- the schema by hand if you prefer, or review exactly what
-- Sequelize is generating.
-- ============================================================

CREATE DATABASE IF NOT EXISTS originhash
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE originhash;

-- ------------------------------------------------------------
-- Table: users
-- Holds Super-admins, Admins, and normal app users
-- (Farmer / Retailer / Distributor / Supplier / Consumer).
-- Normal users log in with mobile + OTP (mobile required, no
-- username/password). Admin and Super-admin accounts log in
-- with username + password instead (mobile optional, OTP login
-- is rejected for is_admin = 1 accounts). is_super_admin further
-- distinguishes accounts that can manage other admin accounts.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id                  INT UNSIGNED NOT NULL AUTO_INCREMENT,
  mobile              VARCHAR(15)  NULL,
  country_code        VARCHAR(5)   NOT NULL DEFAULT '+91',
  username            VARCHAR(50)  NULL,
  password_hash       VARCHAR(255) NULL,
  name                VARCHAR(120) NULL,
  email               VARCHAR(150) NULL,
  photo_url           VARCHAR(500) NULL,
  user_type           ENUM('farmer','retailer','distributor','supplier','consumer') NULL,
  address             VARCHAR(255) NULL,
  is_admin            TINYINT(1)   NOT NULL DEFAULT 0,
  is_super_admin      TINYINT(1)   NOT NULL DEFAULT 0,
  is_blocked          TINYINT(1)   NOT NULL DEFAULT 0,
  profile_completed   TINYINT(1)   NOT NULL DEFAULT 0,
  scans_count         INT UNSIGNED NOT NULL DEFAULT 0,
  created_at          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_mobile (mobile),
  UNIQUE KEY uq_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: otps
-- Stores one-time-passwords issued for login/registration.
-- In this static/demo phase, the OTP is generated by the
-- backend and returned to the frontend to display on screen
-- (no SMS provider wired up yet - 2Factor to be added later).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS otps (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  mobile       VARCHAR(15)  NOT NULL,
  otp_code     VARCHAR(10)  NOT NULL,
  expires_at   DATETIME     NOT NULL,
  is_used      TINYINT(1)   NOT NULL DEFAULT 0,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_otps_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: image_folders / image_assets
-- Admin "Image stock" library: images are organised into
-- named folders and uploaded to S3 under image-stock/<folder name>/.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS image_folders (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name         VARCHAR(120) NOT NULL,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_image_folders_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS image_assets (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  folder_id    INT UNSIGNED NOT NULL,
  file_name    VARCHAR(255) NOT NULL,
  url          VARCHAR(500) NOT NULL,
  width        INT UNSIGNED NULL,
  height       INT UNSIGNED NULL,
  size_bytes   INT UNSIGNED NULL,
  mime_type    VARCHAR(50)  NULL,
  file_hash    VARCHAR(64)  NOT NULL,
  is_blocked   TINYINT(1)   NOT NULL DEFAULT 0,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_image_assets_folder_hash (folder_id, file_hash),
  CONSTRAINT fk_image_assets_folder FOREIGN KEY (folder_id) REFERENCES image_folders (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: qr_batches / qr_codes
-- Admin "Generate QR stickers" tool. One batch = one generation
-- run (producer/product/batch details + a source image folder).
-- Each qr_codes row is one physical unit with its own unique
-- code and a randomly-assigned image from the batch's folder.
-- The PDF export prints 3 sets per batch (1 customer + 2
-- reference) — same codes/images, just extra physical copies.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS qr_batches (
  id             INT UNSIGNED NOT NULL AUTO_INCREMENT,
  producer       VARCHAR(150) NOT NULL,
  product_name   VARCHAR(150) NOT NULL,
  variant_size   VARCHAR(150) NULL,
  batch_no       VARCHAR(80)  NOT NULL,
  split_type     ENUM('vertical-50-50','horizontal-50-50') NOT NULL DEFAULT 'vertical-50-50',
  number_of_qrs  INT UNSIGNED NOT NULL,
  folder_id      INT UNSIGNED NOT NULL,
  created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_qr_batches_folder FOREIGN KEY (folder_id) REFERENCES image_folders (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS qr_codes (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  batch_id      INT UNSIGNED NOT NULL,
  sequence_no   INT UNSIGNED NOT NULL,
  code          VARCHAR(60)  NULL,
  image_url     VARCHAR(500) NOT NULL,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_qr_codes_code (code),
  CONSTRAINT fk_qr_codes_batch FOREIGN KEY (batch_id) REFERENCES qr_batches (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Seed: default Admin account
-- Mobile: 7816018884, static login OTP: 8884
-- (also created automatically by src/utils/seedAdmin.js on boot)
-- ------------------------------------------------------------
INSERT INTO users
  (mobile, country_code, name, is_admin, is_blocked, profile_completed, created_at, updated_at)
VALUES
  ('7816018884', '+91', 'Admin', 1, 0, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE is_admin = 1;

-- ------------------------------------------------------------
-- Example queries used by the API (for reference)
-- ------------------------------------------------------------

-- Find a user by mobile (used at login):
-- SELECT * FROM users WHERE mobile = ? LIMIT 1;

-- Create a new normal user on first OTP request:
-- INSERT INTO users (mobile, country_code, is_admin, is_blocked, profile_completed, created_at, updated_at)
-- VALUES (?, '+91', 0, 0, 0, NOW(), NOW());

-- Store a freshly generated OTP:
-- INSERT INTO otps (mobile, otp_code, expires_at, is_used, created_at)
-- VALUES (?, ?, ?, 0, NOW());

-- Validate an OTP at verify time:
-- SELECT * FROM otps
-- WHERE mobile = ? AND otp_code = ? AND is_used = 0 AND expires_at >= NOW()
-- ORDER BY id DESC LIMIT 1;

-- Mark OTP used:
-- UPDATE otps SET is_used = 1 WHERE id = ?;

-- Update own profile (normal user):
-- UPDATE users
-- SET name = ?, email = ?, user_type = ?, address = ?, photo_url = ?, profile_completed = 1, updated_at = NOW()
-- WHERE id = ?;

-- List users for Admin (search + status filter):
-- SELECT * FROM users
-- WHERE is_admin = 0
--   AND (name LIKE CONCAT('%', ?, '%') OR mobile LIKE CONCAT('%', ?, '%'))
--   AND (? IS NULL OR is_blocked = ?)
-- ORDER BY created_at DESC;

-- Block / unblock a user:
-- UPDATE users SET is_blocked = 1 WHERE id = ?;
-- UPDATE users SET is_blocked = 0 WHERE id = ?;

-- Admin adds a user manually:
-- INSERT INTO users (mobile, country_code, name, email, user_type, address, is_admin, is_blocked, profile_completed, created_at, updated_at)
-- VALUES (?, '+91', ?, ?, ?, ?, 0, 0, 1, NOW(), NOW());
