-- ============================================================
-- OriginHash - Login & User Management module
-- Raw SQL used to design the database tables.
-- Sequelize will also auto-create/sync these same tables on
-- server start, but this file is provided so you can create
-- the schema by hand if you prefer, or review exactly what
-- Sequelize is generating.
-- ============================================================

CREATE DATABASE IF NOT EXISTS originhash
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE originhash;

-- ------------------------------------------------------------
-- Table: users
-- Holds both the Admin user(s) and normal app users
-- (Farmer / Retailer / Distributor / Supplier / Consumer).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id                  INT UNSIGNED NOT NULL AUTO_INCREMENT,
  mobile              VARCHAR(15)  NOT NULL,
  country_code        VARCHAR(5)   NOT NULL DEFAULT '+91',
  name                VARCHAR(120) NULL,
  email               VARCHAR(150) NULL,
  photo_url           VARCHAR(500) NULL,
  user_type           ENUM('farmer','retailer','distributor','supplier','consumer') NULL,
  address             VARCHAR(255) NULL,
  is_admin            TINYINT(1)   NOT NULL DEFAULT 0,
  is_blocked          TINYINT(1)   NOT NULL DEFAULT 0,
  profile_completed   TINYINT(1)   NOT NULL DEFAULT 0,
  scans_count         INT UNSIGNED NOT NULL DEFAULT 0,
  created_at          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: otps
-- Stores one-time-passwords issued for login/registration.
-- In this static/demo phase, the OTP is generated by the
-- backend and returned to the frontend to display on screen
-- (no SMS provider wired up yet - 2Factor to be added later).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS otps (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  mobile       VARCHAR(15)  NOT NULL,
  otp_code     VARCHAR(10)  NOT NULL,
  expires_at   DATETIME     NOT NULL,
  is_used      TINYINT(1)   NOT NULL DEFAULT 0,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_otps_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Seed: default Admin account
-- Mobile: 7816018884, static login OTP: 8884
-- (also created automatically by src/utils/seedAdmin.js on boot)
-- ------------------------------------------------------------
INSERT INTO users
  (mobile, country_code, name, is_admin, is_blocked, profile_completed, created_at, updated_at)
VALUES
  ('7816018884', '+91', 'Admin', 1, 0, 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE is_admin = 1;

-- ------------------------------------------------------------
-- Example queries used by the API (for reference)
-- ------------------------------------------------------------

-- Find a user by mobile (used at login):
-- SELECT * FROM users WHERE mobile = ? LIMIT 1;

-- Create a new normal user on first OTP request:
-- INSERT INTO users (mobile, country_code, is_admin, is_blocked, profile_completed, created_at, updated_at)
-- VALUES (?, '+91', 0, 0, 0, NOW(), NOW());

-- Store a freshly generated OTP:
-- INSERT INTO otps (mobile, otp_code, expires_at, is_used, created_at)
-- VALUES (?, ?, ?, 0, NOW());

-- Validate an OTP at verify time:
-- SELECT * FROM otps
-- WHERE mobile = ? AND otp_code = ? AND is_used = 0 AND expires_at >= NOW()
-- ORDER BY id DESC LIMIT 1;

-- Mark OTP used:
-- UPDATE otps SET is_used = 1 WHERE id = ?;

-- Update own profile (normal user):
-- UPDATE users
-- SET name = ?, email = ?, user_type = ?, address = ?, photo_url = ?, profile_completed = 1, updated_at = NOW()
-- WHERE id = ?;

-- List users for Admin (search + status filter):
-- SELECT * FROM users
-- WHERE is_admin = 0
--   AND (name LIKE CONCAT('%', ?, '%') OR mobile LIKE CONCAT('%', ?, '%'))
--   AND (? IS NULL OR is_blocked = ?)
-- ORDER BY created_at DESC;

-- Block / unblock a user:
-- UPDATE users SET is_blocked = 1 WHERE id = ?;
-- UPDATE users SET is_blocked = 0 WHERE id = ?;

-- Admin adds a user manually:
-- INSERT INTO users (mobile, country_code, name, email, user_type, address, is_admin, is_blocked, profile_completed, created_at, updated_at)
-- VALUES (?, '+91', ?, ?, ?, ?, 0, 0, 1, NOW(), NOW());
